// Run the real dashboard code against a minimal DOM adapter; no bank data is used.
const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
class Element{
 constructor(){this.value='';this.children=[];this.style={};this.textContent='';this.classList={toggle(){}};this.disabled=false;this.open=false;this.dataset={};}
 append(...c){this.children.push(...c);}replaceChildren(...c){this.children=c;if(c.length&&this.isSelect)this.value=c[0].value||c[0].textContent;}
 addEventListener(){}setAttribute(){}getAttribute(){return '200';}getBoundingClientRect(){return {width:340,left:0};}getContext(){return ctx;}showModal(){this.open=true;}close(){this.open=false;}reset(){}
}
const ctx=new Proxy({createLinearGradient(){return {addColorStop(){}};}},{get(o,k){return k in o?o[k]:()=>{};},set(o,k,v){o[k]=v;return true;}}),elements={};
const get=id=>elements[id]||(elements[id]=new Element());['period','bank','trendMode','txStatus','txDirection','editCategory'].forEach(id=>get(id).isSelect=true);get('bank').value='all';get('trendMode').value='daily';get('txStatus').value='all';get('txDirection').value='all';get('txTag').value='all';
const storage=new Map(),sandbox={console,Intl,Date,JSON,Math,Number,String,Object,Array,Set,devicePixelRatio:3,setTimeout:()=>0,setInterval:()=>0,clearTimeout(){},requestAnimationFrame:f=>f(),confirm:()=>true,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},document:{getElementById:get,createElement:()=>new Element(),querySelectorAll:()=>[]}};sandbox.window={addEventListener(){},scrollTo(){}};vm.createContext(sandbox);vm.runInContext(fs.readFileSync('app/src/main/assets/app.js','utf8'),sandbox);
const now=Date.now(),payload={smsGranted:true,transactions:[
{id:'1',time:now,bank:'HDFC',account:'1234',amount:50000,direction:'debit',merchant:'Cafe',category:'Food',status:'confirmed',raw:'test'},
{id:'2',time:now,bank:'KVB',account:'5678',amount:6700000,direction:'credit',merchant:'Employer',category:'Income',status:'confirmed',raw:'test'},
{id:'3',time:now,bank:'HDFC',account:'1234',amount:100000,direction:'debit',merchant:'Uncertain',category:'Other',status:'review',raw:'test'},
{id:'4',time:now,bank:'KVB',account:'5678',amount:200000,direction:'debit',merchant:'Self',category:'Transfer',status:'confirmed',raw:'test'}],plans:[]};
sandbox.window.nativeEvent('snapshot',JSON.stringify(payload));assert.equal(get('expense').textContent,'₹500.00');assert.equal(get('income').textContent,'₹67,000.00');assert.equal(get('net').textContent,'₹66,500.00');console.log('PASS confirmed totals exclude reviews and transfers');
get('bank').value='HDFC';get('bank').onchange();assert.equal(get('income').textContent,'₹0.00');assert.equal(get('expense').textContent,'₹500.00');console.log('PASS bank filter changes totals');
get('txStatus').value='review';get('txStatus').oninput();assert.equal(get('txList').children.length,1);console.log('PASS review filter');
get('available').value='20000';get('expected').value='30000';get('otherCosts').value='25000';get('horizon').value='2099-01-01';payload.plans=[{id:1,name:'Trip',amount:3500000,date:'2098-01-01'},{id:2,name:'Later',amount:100000,date:'2100-01-01'}];sandbox.window.nativeEvent('snapshot',JSON.stringify(payload));assert.equal(get('forecast').textContent,'₹10,000.00');assert.equal(get('forecastLabel').textContent,'Estimated shortfall');console.log('PASS future plan shortfall excludes outside-horizon plans');
get('available').value='';get('available').oninput();assert.equal(get('forecast').textContent,'—');console.log('PASS missing verified balance does not invent forecast');
sandbox.window.nativeEvent('snapshot',JSON.stringify({smsGranted:false,transactions:[],plans:[]}));assert.equal(get('expense').textContent,'₹0.00');assert.equal(get('status').textContent,'SMS access not enabled');console.log('PASS empty state and permission indicator');

console.log('All dashboard checks passed.');

payload.transactions.push({id:'5',time:now,bank:'SBI',account:'9999',amount:10000,direction:'debit',merchant:'Shop',category:'Shopping',status:'confirmed',raw:'test'});sandbox.window.nativeEvent('snapshot',JSON.stringify(payload));assert(get('bank').children.some(o=>o.value==='SBI'));get('bank').value='SBI';get('bank').onchange();assert.equal(get('expense').textContent,'₹100.00');console.log('PASS dynamically detected bank option and totals');
get('bank').value='SBI';payload.transactions[4].bank='Axis';sandbox.window.nativeEvent('snapshot',JSON.stringify(payload));assert.equal(get('bank').value,'all');console.log('PASS missing bank filter resets safely');

get('txStatus').value='all';payload.transactions.push({id:'6',time:now,bank:'SBI',account:'9999',amount:25000,direction:'debit',merchant:'Unknown shop',category:'Uncategorised',status:'confirmed',raw:'test'});sandbox.window.nativeEvent('snapshot',JSON.stringify(payload));get('txTag').value='untagged';get('txTag').oninput();assert.equal(get('txList').children.length,1);assert.equal(get('tagCounts').textContent,'1 untagged · 5 tagged');payload.transactions[5].category='Food';sandbox.window.nativeEvent('snapshot',JSON.stringify(payload));assert.equal(get('txList').children[0].textContent,'No transactions match these filters.');get('txTag').value='tagged';get('txTag').oninput();assert.equal(get('txList').children.length,6);console.log('PASS manual category moves transaction from untagged to tagged');

vm.runInContext("charts();adjustCamera('trend','in');adjustCamera('pie','in');adjustCamera('bars','in');",sandbox);for(const id of ['trend','pie','bars'])assert.equal(get(id).height,600);for(let i=0;i<10;i++)vm.runInContext("lastChartKey='';charts()",sandbox);for(const id of ['trend','pie','bars']){assert.equal(get(id).height,600);assert.equal(get(id).style.height,'200px');}console.log('PASS charts keep fixed height at 3x pixel density across zoom and redraw');
const before=get('txList').children[0];sandbox.window.nativeEvent('snapshot',JSON.stringify(payload));assert.equal(get('txList').children[0],before);console.log('PASS unchanged snapshots do not rebuild dashboard');
sandbox.window.nativeEvent('scanProgress',JSON.stringify({active:true,checked:200,total:1000,added:12,message:'Scanning'}));assert.equal(get('scanProgress').value,20);assert.equal(get('scan').disabled,true);assert(get('scanStats').textContent.includes('12 transactions'));console.log('PASS live scan progress percentage and counts');

get('txTag').value='untagged';payload.transactions[5].category='Uncategorised';sandbox.window.nativeEvent('snapshot',JSON.stringify(payload));let saveArgs;sandbox.window.Ledger={edit(...args){saveArgs=args;}};vm.runInContext("edit(state.transactions.find(t=>t.id==='6'))",sandbox);get('editCategory').value='Travel';get('editForm').onsubmit({preventDefault(){}});assert.equal(get('saveEdit').disabled,true);assert.equal(get('editDialog').open,true);assert.equal(saveArgs[2],'Travel');payload.transactions[5].category='Travel';sandbox.window.nativeEvent('snapshot',JSON.stringify(payload));sandbox.window.nativeEvent('editSaved','6');assert.equal(get('saveEdit').disabled,false);assert.equal(get('editDialog').open,false);assert.equal(get('txList').children[0].textContent,'No transactions match these filters.');console.log('PASS saved edit acknowledges native category before closing and removes untagged row');

get('search').value='nothing matches';get('search').oninput();assert.equal(get('txList').children[0].textContent,'No transactions match these filters.');assert(get('categoryBars').children.some(r=>r.children[0].children[0].textContent==='Travel'));console.log('PASS saved category remains in spending bars when untagged/search filters hide its row');

// Reserve a month-only expense, exclude completed plans, and use explicit reported balances.
payload.plans=[{id:10,name:'Any-day trip',amount:100000,date:'',month:new Date().toISOString().slice(0,7),completed:0},{id:11,name:'Done',amount:900000,date:'',month:new Date().toISOString().slice(0,7),completed:1}];payload.balances=[{bank:'HDFC',account:'1234',amount:200000,time:now},{bank:'KVB',account:'5678',amount:300000,time:now}];payload.notificationsEnabled=true;get('horizon').value=new Date().toISOString().slice(0,7)+'-28';get('expected').value='0';get('otherCosts').value='0';sandbox.window.nativeEvent('snapshot',JSON.stringify(payload));get('useBalances').onclick();assert.equal(get('available').value,5000);assert.equal(get('forecast').textContent,'₹4,000.00');assert.equal(get('balanceList').children.length,2);console.log('PASS month-only forecast, completed plan exclusion and reported balance use');
vm.runInContext("setTimeRange('year')",sandbox);assert.equal(vm.runInContext('timeline.unit',sandbox),'month');vm.runInContext("setTimeRange('day')",sandbox);assert.equal(vm.runInContext('timeline.unit',sandbox),'hour');const span=vm.runInContext('timeline.end-timeline.start',sandbox);vm.runInContext("adjustCamera('trend','out');adjustCamera('trend','out')",sandbox);assert.equal(vm.runInContext('timeline.unit',sandbox),'day');assert(vm.runInContext('timeline.end-timeline.start',sandbox)>span);assert.equal(get('trend').style.height,'200px');vm.runInContext("timeline.start=new Date(2018,0,1).getTime();timeline.end=new Date(2026,0,1).getTime();lastChartKey='';charts()",sandbox);assert.equal(vm.runInContext('timeline.unit',sandbox),'year');console.log('PASS stock-style temporal zoom: years → months → days → hours at fixed height');
