plugins { id 'com.android.application' }
android {
    namespace 'in.pocketledger.app'
    compileSdk 35
    defaultConfig { applicationId 'in.pocketledger.app'; minSdk 26; targetSdk 35; versionCode 7; versionName '1.6'; testInstrumentationRunner 'in.pocketledger.app.LedgerInstrumentation' }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
