package in.pocketledger.app;
import android.app.*;import android.os.*;import android.content.*;import android.database.sqlite.*;import org.json.*;
/** Isolated test database only. Never inserts synthetic SMS or production ledger entries. */
public final class LedgerInstrumentation extends Instrumentation {
 public void onCreate(Bundle args){super.onCreate(args);start();}
 private void check(boolean ok,String message){if(!ok)throw new AssertionError(message);}
 private JSONObject row(Store store)throws Exception{return store.snapshot().getJSONArray("transactions").getJSONObject(0);}
 public void onStart(){Bundle result=new Bundle();Context c=getTargetContext();String name="ledger-regression-only.db";c.deleteDatabase(name);try{
  // Reproduce an older version's stored Untagged Swiggy entry and migrate it.
  SQLiteDatabase old=c.openOrCreateDatabase(name,0,null);old.execSQL("CREATE TABLE tx(id TEXT PRIMARY KEY,time INTEGER,bank TEXT,account TEXT,amount INTEGER,direction TEXT,merchant TEXT,category TEXT,reference TEXT,raw TEXT,sender TEXT,status TEXT,reason TEXT)");old.execSQL("CREATE TABLE rules(merchant TEXT PRIMARY KEY,category TEXT)");old.execSQL("CREATE TABLE plans(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,amount INTEGER,date TEXT)");old.execSQL("INSERT INTO tx VALUES ('test-only',1,'SBI','TEST',50000,'debit','SWIGGYUPI','Uncategorised','','unit-test fixture','VM-SBIUPI','confirmed','isolated test')");old.execSQL("INSERT INTO tx VALUES ('reward-test',2,'Other bank','Unknown',20000,'credit','Unknown','Uncategorised','','Your Swiggy Money is credited with a Gift card of ₹200.00 for Marriott cashback. Total balance is ₹200.00.','VM-SWIGGY','review','isolated test')");old.execSQL("INSERT INTO tx VALUES ('promo-test',3,'Other bank','Unknown',301800,'credit','Unknown','Uncategorised','','ShopHealthy reorder: Your account (9999999999) received Rs.3018 Balance Rs.5929. Unsubscribe','VM-SHPHLT','review','isolated test')");old.setVersion(2);old.close();
  try(Store s=new Store(c,name)){check(s.snapshot().getJSONArray("transactions").length()==1,"Migration removes reward and reorder false matches, retains bank payment");check(row(s).getString("category").equals("Food"),"Existing Swiggy must repair to Food");s.edit("test-only","SBI","Travel","SWIGGYUPI","confirmed","debit",false);check(row(s).getString("category").equals("Travel"),"Manual edit persisted immediately");check(s.applyAutoCategory("SWIGGYUPI","Food")==0,"Online lookup cannot overwrite manual tag");s.repairCategories();check(row(s).getString("category").equals("Travel"),"Repair cannot overwrite manual tag");s.edit("test-only","SBI","Uncategorised","SWIGGYUPI","confirmed","debit",false);s.repairCategories();check(row(s).getString("category").equals("Uncategorised"),"Explicit manual untag respected");}
  // Exercise cleanup when upgrading the currently installed schema, preserving manual tags.
  try(Store s=new Store(c,name)){SQLiteDatabase d=s.getWritableDatabase();d.execSQL("INSERT INTO tx VALUES ('order-reward',4,'Other bank','Unknown',723200,'credit','Unknown','Uncategorised','','ORDER REMINDER: ID#123 on A/C 9999999999 delivered! And you received Rs.7232 reward now. View details example.com/test','VM-VAANAM','review','isolated test',0)");d.execSQL("ALTER TABLE plans RENAME TO plans_new");d.execSQL("CREATE TABLE plans(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,amount INTEGER,date TEXT)");d.execSQL("INSERT INTO plans SELECT id,name,amount,date FROM plans_new");d.execSQL("DROP TABLE plans_new");d.setVersion(4);}
  try(Store s=new Store(c,name)){check(s.snapshot().getJSONArray("transactions").length()==1,"Schema 4 cleanup removes order reward");check(row(s).getString("category").equals("Uncategorised"),"Schema 4 upgrade preserves manual category");}
  try(Store s=new Store(c,name)){s.recordBalance(BalanceParser.parse("VM-HDFCBK","A/c XX1234 Avl Bal INR 9000",100));s.recordBalance(BalanceParser.parse("VM-HDFCBK","A/c XX1234 Avl Bal INR 2000",90));s.recordBalance(BalanceParser.parse("VM-HDFCBK","A/c XX1234 Avl Bal INR 8000",110));check(s.snapshot().getJSONArray("balances").getJSONObject(0).getLong("amount")==800000,"Newest balance wins even scanning newest first");String date=java.time.LocalDate.now().toString(),month=date.substring(0,7);long flexible=s.plan("ISOLATED TEST month-only",10000,"",month),due=s.plan("ISOLATED TEST dated reminder",20000,date,month);check(s.plans().getJSONObject(0).getString("month").equals(month),"Month-only plan persists without day");PlanReminders.deliver(c,s);check(c.getSystemService(android.app.NotificationManager.class).getActiveNotifications().length==1,"Only dated plan posts actual notification");PlanReminders.deliver(c,s);check(c.getSystemService(android.app.NotificationManager.class).getActiveNotifications().length==1,"Reminder does not repeat");s.completePlan(due,true);check(s.plans().getJSONObject(1).getInt("completed")==1,"Completion persists");c.getSystemService(android.app.NotificationManager.class).cancel((int)due);s.removePlan(flexible);}
  result.putString("stream","PASS isolated native DB migration, Swiggy repair, persisted category edits and manual tag preservation and non-bank promotion cleanup, newest account balance, flexible plans and actual dated notification.\n");finish(Activity.RESULT_OK,result);
 }catch(Throwable e){result.putString("stream","FAIL native ledger regression: "+e.toString());finish(Activity.RESULT_CANCELED,result);}finally{c.getSystemService(android.app.NotificationManager.class).cancelAll();c.deleteDatabase(name);}}
}
