package in.pocketledger.app;
import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.database.Cursor;import android.net.Uri;import android.webkit.*;import android.view.*;import java.util.concurrent.*;import java.nio.charset.StandardCharsets;import org.json.*;
public final class MainActivity extends Activity {
 private WebView web;private final ExecutorService worker=Executors.newSingleThreadExecutor();private volatile boolean scanning=false,cancelScan=false;private volatile String scanState="";private volatile String exportText="";
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(0xff0b111d);getWindow().setNavigationBarColor(0xff0b111d);web=new WebView(this);if(Build.VERSION.SDK_INT<30)web.setLayerType(View.LAYER_TYPE_SOFTWARE,null);if((getApplicationInfo().flags & android.content.pm.ApplicationInfo.FLAG_DEBUGGABLE)!=0)WebView.setWebContentsDebuggingEnabled(true);setContentView(web);web.setOnApplyWindowInsetsListener((view,insets)->{view.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets;});web.setBackgroundColor(0xff0b111d);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(false);s.setAllowFileAccessFromFileURLs(false);s.setAllowUniversalAccessFromFileURLs(false);web.addJavascriptInterface(new Bridge(),"Ledger");web.setWebViewClient(new WebViewClient(){public boolean shouldOverrideUrlLoading(WebView w,WebResourceRequest r){return true;}public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){return r.getUrl().toString().startsWith("file:///android_asset/")?null:new WebResourceResponse("text/plain","UTF-8",new java.io.ByteArrayInputStream(new byte[0]));}public void onPageFinished(WebView w,String url){refresh();if(!getPreferences(0).getBoolean("smsPromptShown",false)){getPreferences(0).edit().putBoolean("smsPromptShown",true).apply();if(checkSelfPermission(Manifest.permission.READ_SMS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.READ_SMS,Manifest.permission.RECEIVE_SMS},1);}}});web.loadUrl("file:///android_asset/index.html");}
 public void onResume(){super.onResume();if(web!=null)refresh();}
 private void event(String name,Object value){runOnUiThread(()->web.evaluateJavascript("window.nativeEvent&&window.nativeEvent("+JSONObject.quote(name)+","+JSONObject.quote(String.valueOf(value))+")",null));}
 private void publish(Store store)throws Exception{JSONObject snap=store.snapshot();snap.put("smsGranted",checkSelfPermission(Manifest.permission.READ_SMS)==PackageManager.PERMISSION_GRANTED);if(!scanState.isEmpty())snap.put("scan",new JSONObject(scanState));event("snapshot",snap);}
 private void refresh(){worker.execute(()->{try(Store store=new Store(this)){publish(store);}catch(Exception e){event("error","Could not load data.");}});}
 public void onRequestPermissionsResult(int code,String[] perms,int[] results){super.onRequestPermissionsResult(code,perms,results);refresh();if(checkSelfPermission(Manifest.permission.READ_SMS)==PackageManager.PERMISSION_GRANTED)new Bridge().scanHistory();else event("notice","SMS access was not granted. Enable it in Settings when ready.");}
 private final class ScanTask implements Runnable {
  Cursor cursor;Store store;int checked=0,added=0,total=0;boolean started=false;long lastPublish=0;
  private void progress(boolean active,String message)throws Exception{JSONObject p=new JSONObject();p.put("active",active);p.put("checked",checked);p.put("total",total);p.put("added",added);p.put("message",message);scanState=p.toString();event("scanProgress",scanState);}
  private void finish(String message){scanning=false;try{progress(false,message);if(store!=null)publish(store);}catch(Exception ignored){}finally{if(cursor!=null)cursor.close();if(store!=null)store.close();}event("scanDone",message);}
  public void run(){try{
   if(!started){started=true;store=new Store(MainActivity.this);progress(true,"Opening SMS inbox…");cursor=getContentResolver().query(Uri.parse("content://sms/inbox"),new String[]{"address","body","date"},null,null,"date DESC");total=cursor==null?0:cursor.getCount();}
   if(cancelScan){finish("Scan stopped. Imported entries are saved; scan again to continue.");return;}
   boolean done=cursor==null;int batch=0;long batchStart=SystemClock.elapsedRealtime();android.database.sqlite.SQLiteDatabase db=store.getWritableDatabase();db.beginTransaction();
   try{while(!done&&batch<200&&SystemClock.elapsedRealtime()-batchStart<250){if(!cursor.moveToNext()){done=true;break;}checked++;batch++;SmsParser.Entry entry=SmsParser.parse(cursor.getString(0),cursor.getString(1),cursor.getLong(2));if(entry!=null&&store.insert(entry))added++;}db.setTransactionSuccessful();}finally{db.endTransaction();}
   progress(true,"Scanning bank messages…");long now=SystemClock.elapsedRealtime();if(done||now-lastPublish>=600){publish(store);lastPublish=now;}
   if(done)finish("Scan complete. "+checked+" messages checked; "+added+" new transactions added.");else worker.execute(this);
  }catch(Exception e){finish("Scan interrupted. Imported entries are saved. Check SMS access and retry.");event("error","SMS scan interrupted; your imported entries are saved.");}}
 }
 public final class Bridge {
  @JavascriptInterface public void permissions(){runOnUiThread(()->requestPermissions(new String[]{Manifest.permission.READ_SMS,Manifest.permission.RECEIVE_SMS},1));}
  @JavascriptInterface public void refreshData(){refresh();}
  @JavascriptInterface public synchronized void scanHistory(){if(scanning)return;if(checkSelfPermission(Manifest.permission.READ_SMS)!=PackageManager.PERMISSION_GRANTED){event("error","Grant SMS permission first.");return;}scanning=true;cancelScan=false;worker.execute(new ScanTask());}
  @JavascriptInterface public void stopScan(){cancelScan=true;}
  @JavascriptInterface public void edit(String id,String bank,String cat,String merchant,String status,String direction,boolean learn){worker.execute(()->{try(Store s=new Store(MainActivity.this)){s.edit(id,bank,cat,merchant,status,direction,learn);publish(s);event("editSaved",id);}catch(Exception e){event("error","Could not save changes. Please retry.");}});}
  @JavascriptInterface public void addPlan(String name,long amount,String date){if(name.trim().isEmpty()||amount<=0||!date.matches("\\d{4}-\\d{2}-\\d{2}"))return;worker.execute(()->{try(Store s=new Store(MainActivity.this)){s.plan(name,amount,date);refresh();}});}
  @JavascriptInterface public void deletePlan(long id){worker.execute(()->{try(Store s=new Store(MainActivity.this)){s.removePlan(id);refresh();}});}
  @JavascriptInterface public void exportCsv(){worker.execute(()->{try(Store s=new Store(MainActivity.this)){JSONArray a=s.snapshot().getJSONArray("transactions");StringBuilder out=new StringBuilder("Date,Bank,Account,Amount INR,Direction,Merchant,Category,Status,Reference\n");for(int i=0;i<a.length();i++){JSONObject t=a.getJSONObject(i);out.append(csv(new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm",java.util.Locale.ROOT).format(new java.util.Date(t.getLong("time"))))).append(',');for(String key:new String[]{"bank","account"})out.append(csv(t.optString(key))).append(',');out.append(t.getLong("amount")/100.0).append(',');for(String key:new String[]{"direction","merchant","category","status"})out.append(csv(t.optString(key))).append(',');out.append(csv(t.optString("reference"))).append('\n');}exportText=out.toString();runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("text/csv");i.addCategory(Intent.CATEGORY_OPENABLE);i.putExtra(Intent.EXTRA_TITLE,"PocketLedger-transactions.csv");startActivityForResult(i,2);});}catch(Exception e){event("error","Export failed.");}});}
  @JavascriptInterface public void clearData(){cancelScan=true;runOnUiThread(()->new AlertDialog.Builder(MainActivity.this).setTitle("Delete all tracker data?").setMessage("This deletes imported transactions, rules and plans. Your phone SMS messages remain.").setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,w)->worker.execute(()->{try(Store s=new Store(MainActivity.this)){s.clear();event("cleared","");refresh();}})).show());}
 }
 private static String csv(String s){if(s.matches("^[=+@\\-].*"))s="'"+s;return "\""+s.replace("\"","\"\"")+"\"";}
 protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==2&&result==RESULT_OK&&data!=null){worker.execute(()->{try(java.io.OutputStream out=getContentResolver().openOutputStream(data.getData())){out.write(exportText.getBytes(StandardCharsets.UTF_8));event("notice","CSV saved.");}catch(Exception e){event("error","Could not save CSV.");}});}}
 public void onBackPressed(){runOnUiThread(()->web.evaluateJavascript("window.closeDialog&&window.closeDialog()",null));}
}
