package in.pocketledger.app;
import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.database.Cursor;import android.net.Uri;import android.webkit.*;import android.view.*;import java.util.concurrent.*;import java.nio.charset.StandardCharsets;import org.json.*;
public final class MainActivity extends Activity {
 private long lastBalanceFetch=0;private WebView web;private final ExecutorService lookupWorker=Executors.newSingleThreadExecutor();private final java.util.Map<String,Long> lookupTimes=new java.util.concurrent.ConcurrentHashMap<>();private final ExecutorService worker=Executors.newSingleThreadExecutor();private volatile boolean scanning=false,cancelScan=false;private volatile String scanState="";private volatile String exportText="";
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(0xfff5f5f7);getWindow().setNavigationBarColor(0xfff5f5f7);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);web=new WebView(this);if(Build.VERSION.SDK_INT<30)web.setLayerType(View.LAYER_TYPE_SOFTWARE,null);if((getApplicationInfo().flags & android.content.pm.ApplicationInfo.FLAG_DEBUGGABLE)!=0)WebView.setWebContentsDebuggingEnabled(true);setContentView(web);web.setOnApplyWindowInsetsListener((view,insets)->{view.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets;});web.setBackgroundColor(0xfff5f5f7);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(false);s.setAllowFileAccessFromFileURLs(false);s.setAllowUniversalAccessFromFileURLs(false);web.addJavascriptInterface(new Bridge(),"Ledger");web.setWebViewClient(new WebViewClient(){public boolean shouldOverrideUrlLoading(WebView w,WebResourceRequest r){return true;}public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){return r.getUrl().toString().startsWith("file:///android_asset/")?null:new WebResourceResponse("text/plain","UTF-8",new java.io.ByteArrayInputStream(new byte[0]));}public void onPageFinished(WebView w,String url){refresh();if(!getPreferences(0).getBoolean("smsPromptShown",false)){getPreferences(0).edit().putBoolean("smsPromptShown",true).apply();if(checkSelfPermission(Manifest.permission.READ_SMS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.READ_SMS,Manifest.permission.RECEIVE_SMS},1);}}});web.loadUrl("file:///android_asset/index.html");}
 public void onResume(){super.onResume();worker.execute(()->{PlanReminders.deliver(this);PlanReminders.schedule(this);});if(web!=null)refresh();}
 private void event(String name,Object value){runOnUiThread(()->web.evaluateJavascript("window.nativeEvent&&window.nativeEvent("+JSONObject.quote(name)+","+JSONObject.quote(String.valueOf(value))+")",null));}
 private void publish(Store store)throws Exception{JSONObject snap=store.snapshot();snap.put("notificationsEnabled",PlanReminders.enabled(this));snap.put("openPlans",getIntent().getBooleanExtra("openPlans",false));getIntent().removeExtra("openPlans");snap.put("googleConfigured",!getPreferences(0).getString("googleKey","").isEmpty());snap.put("smsGranted",checkSelfPermission(Manifest.permission.READ_SMS)==PackageManager.PERMISSION_GRANTED);if(!scanState.isEmpty())snap.put("scan",new JSONObject(scanState));event("snapshot",snap);}
 private void refresh(){worker.execute(()->{try(Store store=new Store(this)){if(System.currentTimeMillis()-lastBalanceFetch>30000&&checkSelfPermission(Manifest.permission.READ_SMS)==PackageManager.PERMISSION_GRANTED){lastBalanceFetch=System.currentTimeMillis();try(Cursor c=getContentResolver().query(Uri.parse("content://sms/inbox"),new String[]{"address","body","date"},null,null,"date DESC")){int read=0;while(c!=null&&read++<200&&c.moveToNext())store.recordBalance(BalanceParser.parse(c.getString(0),c.getString(1),c.getLong(2)));}}publish(store);}catch(Exception e){event("error","Could not load data.");}});}
 public void onRequestPermissionsResult(int code,String[] perms,int[] results){super.onRequestPermissionsResult(code,perms,results);if(code==3){PlanReminders.deliver(this);PlanReminders.schedule(this);refresh();return;}refresh();if(checkSelfPermission(Manifest.permission.READ_SMS)==PackageManager.PERMISSION_GRANTED)new Bridge().scanHistory();else event("notice","SMS access was not granted. Enable it in Settings when ready.");}
 private final class ScanTask implements Runnable {
  Cursor cursor;Store store;int checked=0,added=0,total=0;boolean started=false;long lastPublish=0;
  private void progress(boolean active,String message)throws Exception{JSONObject p=new JSONObject();p.put("active",active);p.put("checked",checked);p.put("total",total);p.put("added",added);p.put("message",message);scanState=p.toString();event("scanProgress",scanState);}
  private void finish(String message){scanning=false;try{progress(false,message);if(store!=null)publish(store);}catch(Exception ignored){}finally{if(cursor!=null)cursor.close();if(store!=null)store.close();}event("scanDone",message);}
  public void run(){try{
   if(!started){started=true;store=new Store(MainActivity.this);progress(true,"Opening SMS inbox…");cursor=getContentResolver().query(Uri.parse("content://sms/inbox"),new String[]{"address","body","date"},null,null,"date DESC");total=cursor==null?0:cursor.getCount();}
   if(cancelScan){finish("Scan stopped. Imported entries are saved; scan again to continue.");return;}
   boolean done=cursor==null;int batch=0;long batchStart=SystemClock.elapsedRealtime();android.database.sqlite.SQLiteDatabase db=store.getWritableDatabase();db.beginTransaction();
   try{while(!done&&batch<200&&SystemClock.elapsedRealtime()-batchStart<250){if(!cursor.moveToNext()){done=true;break;}checked++;batch++;store.recordBalance(BalanceParser.parse(cursor.getString(0),cursor.getString(1),cursor.getLong(2)));SmsParser.Entry entry=SmsParser.parse(cursor.getString(0),cursor.getString(1),cursor.getLong(2));if(entry!=null&&store.insert(entry))added++;}db.setTransactionSuccessful();}finally{db.endTransaction();}
   progress(true,"Scanning bank messages…");long now=SystemClock.elapsedRealtime();if(done||now-lastPublish>=600){publish(store);lastPublish=now;}
   if(done)finish("Scan complete. "+checked+" messages checked; "+added+" new transactions added.");else worker.execute(this);
  }catch(Exception e){finish("Scan interrupted. Imported entries are saved. Check SMS access and retry.");event("error","SMS scan interrupted; your imported entries are saved.");}}
 }
 private void lookupEvent(String query,String message){try{JSONObject data=new JSONObject();data.put("query",query);data.put("message",message);event("lookupStatus",data);}catch(Exception ignored){}}
 public final class Bridge {
  @JavascriptInterface public void saveGoogleKey(String key){getPreferences(0).edit().putString("googleKey",key.trim()).apply();lookupTimes.clear();refresh();event("notice",key.trim().isEmpty()?"Google lookup disabled. Built-in merchant categories remain available.":"Google Places key saved on this phone.");}
  @JavascriptInterface public void cleanNonBankAlerts(){worker.execute(()->{try(Store s=new Store(MainActivity.this)){int count=s.removeNonBankAlerts();publish(s);event("notice","Removed "+count+" non-bank alerts. Phone SMS were kept.");}catch(Exception e){event("error","Could not clean imported alerts.");}});}
  @JavascriptInterface public void repairCategories(){worker.execute(()->{try(Store s=new Store(MainActivity.this)){int count=s.repairCategories();publish(s);event("notice","Updated "+count+" recognised Untagged entries.");}catch(Exception e){event("error","Could not update categories.");}});}
  @JavascriptInterface public void lookupSearch(String query){if(query.trim().length()<3)return;worker.execute(()->{try(Store s=new Store(MainActivity.this)){s.repairCategories();publish(s);java.util.List<String> merchants=s.untaggedMerchants(query.trim());if(merchants.isEmpty()){lookupEvent(query,"Recognised merchants tagged; no remaining matching entries need lookup.");return;}if(getPreferences(0).getString("googleKey","").isEmpty()){lookupEvent(query,"Add your Google Places key in Settings for online lookup. Unknown merchants stay Untagged.");return;}lookupEvent(query,"Checking business categories on Google Maps…");lookupWorker.execute(()->{int changed=0;boolean failed=false;String source="";for(String merchant:merchants){long now=System.currentTimeMillis();Long last=lookupTimes.get(merchant);if(last!=null&&now-last<60000)continue;lookupTimes.put(merchant,now);try{MerchantLookup.Result result=MerchantLookup.lookup(merchant,getPreferences(0).getString("googleKey",""));if(!result.category.equals("Uncategorised")){try(Store update=new Store(MainActivity.this)){changed+=update.applyAutoCategory(merchant,result.category);}source=result.source;refresh();}}catch(Exception e){failed=true;}}lookupEvent(query,changed>0?"Tagged "+changed+" entries from "+source+". Manual tags were kept.":failed?"Online lookup unavailable. Kept Untagged; check Internet or Google key.":"No confident business match. Kept Untagged.");});}catch(Exception e){lookupEvent(query,"Could not check merchant categories.");}});}

  @JavascriptInterface public void permissions(){runOnUiThread(()->requestPermissions(new String[]{Manifest.permission.READ_SMS,Manifest.permission.RECEIVE_SMS},1));}
  @JavascriptInterface public void refreshData(){refresh();}
  @JavascriptInterface public synchronized void scanHistory(){if(scanning)return;if(checkSelfPermission(Manifest.permission.READ_SMS)!=PackageManager.PERMISSION_GRANTED){event("error","Grant SMS permission first.");return;}scanning=true;cancelScan=false;worker.execute(new ScanTask());}
  @JavascriptInterface public void stopScan(){cancelScan=true;}
  @JavascriptInterface public void edit(String id,String bank,String cat,String merchant,String status,String direction,boolean learn){worker.execute(()->{try(Store s=new Store(MainActivity.this)){s.edit(id,bank,cat,merchant,status,direction,learn);publish(s);event("editSaved",id);}catch(Exception e){event("error","Could not save changes. Please retry.");}});}
  @JavascriptInterface public void notificationAccess(){runOnUiThread(()->{if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},3);else startActivity(new Intent(android.provider.Settings.ACTION_APP_NOTIFICATION_SETTINGS).putExtra(android.provider.Settings.EXTRA_APP_PACKAGE,getPackageName()));});}
  @JavascriptInterface public void addPlan(String name,long amount,String date,String month){worker.execute(()->{try(Store s=new Store(MainActivity.this)){s.plan(name,amount,date,month);PlanReminders.deliver(MainActivity.this);PlanReminders.schedule(MainActivity.this);publish(s);event("planSaved",date.isEmpty()?"Plan saved for "+month+". No date reminder.":"Plan saved. Morning reminder on "+date+".");}catch(Exception e){event("error","Could not save plan. Check description, amount and date.");}});}
  @JavascriptInterface public void completePlan(long id,boolean done){worker.execute(()->{try(Store s=new Store(MainActivity.this)){s.completePlan(id,done);PlanReminders.cancel(MainActivity.this,id);publish(s);}});}
  @JavascriptInterface public void deletePlan(long id){worker.execute(()->{try(Store s=new Store(MainActivity.this)){s.removePlan(id);PlanReminders.cancel(MainActivity.this,id);publish(s);}});}
  @JavascriptInterface public void exportCsv(){worker.execute(()->{try(Store s=new Store(MainActivity.this)){JSONArray a=s.snapshot().getJSONArray("transactions");StringBuilder out=new StringBuilder("Date,Bank,Account,Amount INR,Direction,Merchant,Category,Status,Reference\n");for(int i=0;i<a.length();i++){JSONObject t=a.getJSONObject(i);out.append(csv(new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm",java.util.Locale.ROOT).format(new java.util.Date(t.getLong("time"))))).append(',');for(String key:new String[]{"bank","account"})out.append(csv(t.optString(key))).append(',');out.append(t.getLong("amount")/100.0).append(',');for(String key:new String[]{"direction","merchant","category","status"})out.append(csv(t.optString(key))).append(',');out.append(csv(t.optString("reference"))).append('\n');}exportText=out.toString();runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("text/csv");i.addCategory(Intent.CATEGORY_OPENABLE);i.putExtra(Intent.EXTRA_TITLE,"PocketLedger-transactions.csv");startActivityForResult(i,2);});}catch(Exception e){event("error","Export failed.");}});}
  @JavascriptInterface public void clearData(){cancelScan=true;runOnUiThread(()->new AlertDialog.Builder(MainActivity.this).setTitle("Delete all tracker data?").setMessage("This deletes imported transactions, rules and plans. Your phone SMS messages remain.").setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,w)->worker.execute(()->{try(Store s=new Store(MainActivity.this)){s.clear();PlanReminders.schedule(MainActivity.this);getSystemService(NotificationManager.class).cancelAll();event("cleared","");refresh();}})).show());}
 }
 private static String csv(String s){if(s.matches("^[=+@\\-].*"))s="'"+s;return "\""+s.replace("\"","\"\"")+"\"";}
 protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==2&&result==RESULT_OK&&data!=null){worker.execute(()->{try(java.io.OutputStream out=getContentResolver().openOutputStream(data.getData())){out.write(exportText.getBytes(StandardCharsets.UTF_8));event("notice","CSV saved.");}catch(Exception e){event("error","Could not save CSV.");}});}}
 public void onBackPressed(){runOnUiThread(()->web.evaluateJavascript("window.closeDialog&&window.closeDialog()",null));}
}
