package in.pocketledger.app;
import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.database.Cursor;import android.net.Uri;import android.webkit.*;import android.view.*;import java.util.concurrent.*;import java.nio.charset.StandardCharsets;import org.json.*;
public final class MainActivity extends Activity {
 private WebView web;private final ExecutorService worker=Executors.newSingleThreadExecutor();private volatile boolean scanning=false;private volatile String exportText="";
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(0xff0b111d);getWindow().setNavigationBarColor(0xff0b111d);web=new WebView(this);if(Build.VERSION.SDK_INT<30)web.setLayerType(View.LAYER_TYPE_SOFTWARE,null);if((getApplicationInfo().flags & android.content.pm.ApplicationInfo.FLAG_DEBUGGABLE)!=0)WebView.setWebContentsDebuggingEnabled(true);setContentView(web);web.setOnApplyWindowInsetsListener((view,insets)->{view.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets;});web.setBackgroundColor(0xff0b111d);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(false);s.setAllowFileAccessFromFileURLs(false);s.setAllowUniversalAccessFromFileURLs(false);web.addJavascriptInterface(new Bridge(),"Ledger");web.setWebViewClient(new WebViewClient(){public boolean shouldOverrideUrlLoading(WebView w,WebResourceRequest r){return true;}public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){return r.getUrl().toString().startsWith("file:///android_asset/")?null:new WebResourceResponse("text/plain","UTF-8",new java.io.ByteArrayInputStream(new byte[0]));}public void onPageFinished(WebView w,String url){refresh();}});web.loadUrl("file:///android_asset/index.html");}
 public void onResume(){super.onResume();if(web!=null)refresh();}
 private void event(String name,Object value){runOnUiThread(()->web.evaluateJavascript("window.nativeEvent&&window.nativeEvent("+JSONObject.quote(name)+","+JSONObject.quote(String.valueOf(value))+")",null));}
 private void refresh(){worker.execute(()->{try(Store store=new Store(this)){JSONObject snap=store.snapshot();snap.put("smsGranted",checkSelfPermission(Manifest.permission.READ_SMS)==PackageManager.PERMISSION_GRANTED);event("snapshot",snap);}catch(Exception e){event("error","Could not load data.");}});}
 public void onRequestPermissionsResult(int code,String[] perms,int[] results){super.onRequestPermissionsResult(code,perms,results);refresh();event("notice","Permissions updated. Tap Scan history to import existing messages.");}
 public final class Bridge {
  @JavascriptInterface public void permissions(){runOnUiThread(()->requestPermissions(new String[]{Manifest.permission.READ_SMS,Manifest.permission.RECEIVE_SMS},1));}
  @JavascriptInterface public void refreshData(){refresh();}
  @JavascriptInterface public void scanHistory(){if(scanning)return;if(checkSelfPermission(Manifest.permission.READ_SMS)!=PackageManager.PERMISSION_GRANTED){event("error","Grant SMS permission first.");return;}scanning=true;worker.execute(()->{int found=0,total=0;try(Store store=new Store(MainActivity.this);Cursor c=getContentResolver().query(Uri.parse("content://sms/inbox"),new String[]{"address","body","date"},null,null,"date ASC")){if(c!=null)while(c.moveToNext()){total++;SmsParser.Entry e=SmsParser.parse(c.getString(0),c.getString(1),c.getLong(2));if(e!=null&&store.insert(e))found++;}event("notice","Scanned "+total+" messages; added "+found+" bank entries. Review uncertain entries.");}catch(Exception e){event("error","SMS scan failed. Check permission and retry.");}finally{scanning=false;refresh();event("scanDone","");}});}
  @JavascriptInterface public void edit(String id,String bank,String cat,String merchant,String status,String direction,boolean learn){worker.execute(()->{try(Store s=new Store(MainActivity.this)){s.edit(id,bank,cat,merchant,status,direction,learn);refresh();}catch(Exception e){event("error","Could not save changes.");}});}
  @JavascriptInterface public void addPlan(String name,long amount,String date){if(name.trim().isEmpty()||amount<=0||!date.matches("\\d{4}-\\d{2}-\\d{2}"))return;worker.execute(()->{try(Store s=new Store(MainActivity.this)){s.plan(name,amount,date);refresh();}});}
  @JavascriptInterface public void deletePlan(long id){worker.execute(()->{try(Store s=new Store(MainActivity.this)){s.removePlan(id);refresh();}});}
  @JavascriptInterface public void exportCsv(){worker.execute(()->{try(Store s=new Store(MainActivity.this)){JSONArray a=s.snapshot().getJSONArray("transactions");StringBuilder out=new StringBuilder("Date,Bank,Account,Amount INR,Direction,Merchant,Category,Status,Reference\n");for(int i=0;i<a.length();i++){JSONObject t=a.getJSONObject(i);out.append(csv(new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm",java.util.Locale.ROOT).format(new java.util.Date(t.getLong("time"))))).append(',');for(String key:new String[]{"bank","account"})out.append(csv(t.optString(key))).append(',');out.append(t.getLong("amount")/100.0).append(',');for(String key:new String[]{"direction","merchant","category","status"})out.append(csv(t.optString(key))).append(',');out.append(csv(t.optString("reference"))).append('\n');}exportText=out.toString();runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("text/csv");i.addCategory(Intent.CATEGORY_OPENABLE);i.putExtra(Intent.EXTRA_TITLE,"PocketLedger-transactions.csv");startActivityForResult(i,2);});}catch(Exception e){event("error","Export failed.");}});}
  @JavascriptInterface public void clearData(){runOnUiThread(()->new AlertDialog.Builder(MainActivity.this).setTitle("Delete all tracker data?").setMessage("This deletes imported transactions, rules and plans. Your phone SMS messages remain.").setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,w)->worker.execute(()->{try(Store s=new Store(MainActivity.this)){s.clear();event("cleared","");refresh();}})).show());}
 }
 private static String csv(String s){if(s.matches("^[=+@\\-].*"))s="'"+s;return "\""+s.replace("\"","\"\"")+"\"";}
 protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==2&&result==RESULT_OK&&data!=null){worker.execute(()->{try(java.io.OutputStream out=getContentResolver().openOutputStream(data.getData())){out.write(exportText.getBytes(StandardCharsets.UTF_8));event("notice","CSV saved.");}catch(Exception e){event("error","Could not save CSV.");}});}}
 public void onBackPressed(){runOnUiThread(()->web.evaluateJavascript("window.closeDialog&&window.closeDialog()",null));}
}
