package in.pocketledger.app;
import android.app.*;import android.content.*;import android.os.*;import org.json.*;import java.time.*;
/** One local day-level alarm, restored on reboot and clock changes. Month-only plans never invent dates. */
public final class PlanReminders extends BroadcastReceiver {
 static final String CHANNEL="future-plans";
 public void onReceive(Context c,Intent i){deliver(c);schedule(c);}
 static PendingIntent alarm(Context c){return PendingIntent.getBroadcast(c,0,new Intent(c,PlanReminders.class).setAction("in.pocketledger.app.PLAN_REMINDER"),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);}
 public static boolean enabled(Context c){NotificationManager n=c.getSystemService(NotificationManager.class);n.createNotificationChannel(new NotificationChannel(CHANNEL,"Future expense reminders",NotificationManager.IMPORTANCE_DEFAULT));NotificationChannel ch=n.getNotificationChannel(CHANNEL);return n.areNotificationsEnabled()&&ch.getImportance()!=NotificationManager.IMPORTANCE_NONE;}
 public static void schedule(Context c){AlarmManager a=c.getSystemService(AlarmManager.class);a.cancel(alarm(c));try(Store s=new Store(c)){JSONArray plans=s.plans();long next=Long.MAX_VALUE,now=System.currentTimeMillis();for(int j=0;j<plans.length();j++){JSONObject p=plans.getJSONObject(j);if(p.optInt("completed")==1||p.optInt("notified")==1||p.optString("date").isEmpty())continue;long t=LocalDate.parse(p.getString("date")).atTime(9,0).atZone(ZoneId.systemDefault()).toInstant().toEpochMilli();if(t<=now)t=LocalDate.now().plusDays(1).atTime(9,0).atZone(ZoneId.systemDefault()).toInstant().toEpochMilli();next=Math.min(next,t);}if(next!=Long.MAX_VALUE)a.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,next,alarm(c));}catch(Exception ignored){}}
 public static void deliver(Context c){try(Store s=new Store(c)){deliver(c,s);}catch(Exception ignored){}}
 static void deliver(Context c,Store s)throws Exception{if(!enabled(c))return;String today=LocalDate.now().toString();JSONArray plans=s.plans();for(int j=0;j<plans.length();j++){JSONObject p=plans.getJSONObject(j);String date=p.optString("date");if(date.isEmpty()||date.compareTo(today)>0||p.optInt("completed")==1||p.optInt("notified")==1)continue;int id=p.getInt("id");String text="You planned "+p.getString("name")+" · ₹"+String.format(java.util.Locale.US,"%.2f",p.getLong("amount")/100.0)+(date.equals(today)?" for today.":" for "+date+".");PendingIntent open=PendingIntent.getActivity(c,id,new Intent(c,MainActivity.class).putExtra("openPlans",true),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification n=new Notification.Builder(c,CHANNEL).setSmallIcon(android.R.drawable.ic_menu_my_calendar).setContentTitle("Your plan is due").setContentText(text).setStyle(new Notification.BigTextStyle().bigText(text)).setContentIntent(open).setAutoCancel(true).setVisibility(Notification.VISIBILITY_PRIVATE).build();c.getSystemService(NotificationManager.class).notify(id,n);s.notified(id);}}
 public static void cancel(Context c,long id){c.getSystemService(NotificationManager.class).cancel((int)id);schedule(c);}
}
