package in.pocketledger.app;
import android.content.*;import android.database.*;import android.database.sqlite.*;import org.json.*;import java.security.*;import java.nio.charset.StandardCharsets;
public final class Store extends SQLiteOpenHelper {
 public Store(Context c){this(c,"ledger.db");}
 public Store(Context c,String databaseName){super(c,databaseName,null,4);}
 public void onCreate(SQLiteDatabase d){d.execSQL("CREATE TABLE tx(id TEXT PRIMARY KEY,time INTEGER,bank TEXT,account TEXT,amount INTEGER,direction TEXT,merchant TEXT,category TEXT,reference TEXT,raw TEXT,sender TEXT,status TEXT,reason TEXT,manualCategory INTEGER NOT NULL DEFAULT 0)");d.execSQL("CREATE TABLE rules(merchant TEXT PRIMARY KEY,category TEXT)");d.execSQL("CREATE TABLE plans(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,amount INTEGER,date TEXT)");indexes(d);}
 public void onUpgrade(SQLiteDatabase d,int a,int b){if(a<4)removeNonBankAlerts(d);if(a<3){d.execSQL("ALTER TABLE tx ADD COLUMN manualCategory INTEGER NOT NULL DEFAULT 0");d.execSQL("UPDATE tx SET manualCategory=1 WHERE category<>'Uncategorised'");repair(d);}indexes(d);}
 private void indexes(SQLiteDatabase d){d.execSQL("CREATE INDEX IF NOT EXISTS tx_duplicates ON tx(bank,amount,direction)");d.execSQL("CREATE INDEX IF NOT EXISTS tx_time ON tx(time DESC)");d.execSQL("CREATE INDEX IF NOT EXISTS tx_merchant ON tx(merchant COLLATE NOCASE)");}
 public boolean insert(SmsParser.Entry e){
  SQLiteDatabase d=getWritableDatabase();String id=hash(e.sender+"|"+e.raw+"|"+e.time);try(Cursor existing=d.rawQuery("SELECT id FROM tx WHERE id=?",new String[]{id})){if(existing.moveToFirst()){repairEntry(d,id,e);return false;}}ContentValues v=new ContentValues();v.put("id",id);v.put("time",e.time);v.put("bank",e.bank);v.put("account",e.account);v.put("amount",e.amountPaise);v.put("direction",e.direction);v.put("merchant",e.merchant);v.put("category",e.category);v.put("reference",e.reference);v.put("raw",e.raw);v.put("sender",e.sender);v.put("status",e.status);v.put("reason",e.reason);
  try(Cursor c=d.rawQuery("SELECT category FROM rules WHERE merchant=?",new String[]{e.merchant.trim().toLowerCase(java.util.Locale.ROOT)})){if(c.moveToFirst()){v.put("category",c.getString(0));v.put("manualCategory",1);}}
  // Exact source duplicates are ignored. Possible repeated alerts are retained for review.
  try(Cursor c=d.rawQuery("SELECT id FROM tx WHERE bank=? AND amount=? AND direction=? AND ((reference<>'' AND reference=?) OR (raw=? AND ABS(time-?)<120000)) LIMIT 1",new String[]{e.bank,""+e.amountPaise,e.direction,e.reference,e.raw,""+e.time})){if(c.moveToFirst()){v.put("status","review");v.put("reason","Possible duplicate alert; compare with existing transaction before including.");}}
  return d.insertWithOnConflict("tx",null,v,SQLiteDatabase.CONFLICT_IGNORE)!=-1;
 }
 public JSONObject snapshot()throws Exception{JSONObject o=new JSONObject();o.put("transactions",rows("SELECT * FROM tx ORDER BY time DESC"));o.put("plans",rows("SELECT * FROM plans ORDER BY date"));return o;}
 private JSONArray rows(String sql)throws Exception{JSONArray a=new JSONArray();try(Cursor c=getReadableDatabase().rawQuery(sql,null)){while(c.moveToNext()){JSONObject o=new JSONObject();for(int i=0;i<c.getColumnCount();i++){if(c.getType(i)==Cursor.FIELD_TYPE_INTEGER)o.put(c.getColumnName(i),c.getLong(i));else o.put(c.getColumnName(i),c.getString(i));}a.put(o);}}return a;}
 public void edit(String id,String bank,String category,String merchant,String status,String direction,boolean learn){
  if(!java.util.Arrays.asList("confirmed","review","excluded").contains(status)||!java.util.Arrays.asList("debit","credit").contains(direction)||!java.util.Arrays.asList("Uncategorised","Food","Travel","Shopping","Groceries","Bills","Health","Entertainment","Income","Transfer","Other").contains(category))throw new IllegalArgumentException("Invalid edit");
  String name=merchant.trim().isEmpty()?"Unknown":merchant.trim();SQLiteDatabase db=getWritableDatabase();db.beginTransaction();try{ContentValues v=new ContentValues();v.put("bank",bank.trim().isEmpty()?"Other bank":bank.trim());v.put("category",category);v.put("manualCategory",1);v.put("merchant",name);v.put("status",status);v.put("direction",direction);if(db.update("tx",v,"id=?",new String[]{id})!=1)throw new IllegalArgumentException("Entry missing");if(learn&&!name.equalsIgnoreCase("Unknown")){ContentValues rule=new ContentValues();rule.put("merchant",name.toLowerCase(java.util.Locale.ROOT));rule.put("category",category);db.insertWithOnConflict("rules",null,rule,SQLiteDatabase.CONFLICT_REPLACE);ContentValues cat=new ContentValues();cat.put("category",category);cat.put("manualCategory",1);db.update("tx",cat,"LOWER(TRIM(merchant))=?",new String[]{name.toLowerCase(java.util.Locale.ROOT)});}db.setTransactionSuccessful();}finally{db.endTransaction();}
 }

 private void repairEntry(SQLiteDatabase d,String id,SmsParser.Entry e){try(Cursor c=d.rawQuery("SELECT merchant FROM tx WHERE id=? AND category='Uncategorised' AND manualCategory=0",new String[]{id})){if(c.moveToFirst()){String merchant=c.getString(0),category=SmsParser.categorise(merchant);if(category.equals("Uncategorised")&&e!=null){merchant=e.merchant;category=e.category;}if(!category.equals("Uncategorised")){ContentValues v=new ContentValues();v.put("merchant",merchant);v.put("category",category);d.update("tx",v,"id=? AND category='Uncategorised' AND manualCategory=0",new String[]{id});}}}}
 private int repair(SQLiteDatabase d){int count=0;try(Cursor c=d.rawQuery("SELECT id,merchant,sender,raw,time FROM tx WHERE category='Uncategorised' AND manualCategory=0",null)){while(c.moveToNext()){String merchant=c.getString(1);String category=SmsParser.categorise(merchant);if(category.equals("Uncategorised")){SmsParser.Entry e=SmsParser.parse(c.getString(2),c.getString(3),c.getLong(4));if(e!=null){merchant=e.merchant;category=e.category;}}if(!category.equals("Uncategorised")){ContentValues v=new ContentValues();v.put("merchant",merchant);v.put("category",category);count+=d.update("tx",v,"id=? AND category='Uncategorised' AND manualCategory=0",new String[]{c.getString(0)});}}}return count;}
 private int removeNonBankAlerts(SQLiteDatabase d){java.util.List<String> ids=new java.util.ArrayList<>();try(Cursor c=d.rawQuery("SELECT id,sender,raw,status FROM tx",null)){while(c.moveToNext()){String reason=SmsParser.rejectionReason(c.getString(1),c.getString(2));if(!reason.isEmpty()&&(c.getString(3).equals("review")||reason.startsWith("Promotion")||reason.startsWith("Merchant")))ids.add(c.getString(0));}}int removed=0;for(String id:ids)removed+=d.delete("tx","id=?",new String[]{id});return removed;}
 public int removeNonBankAlerts(){return removeNonBankAlerts(getWritableDatabase());}
 public int repairCategories(){return repair(getWritableDatabase());}
 public java.util.List<String> untaggedMerchants(String query){java.util.List<String> merchants=new java.util.ArrayList<>();String q=query.toLowerCase(java.util.Locale.ROOT);try(Cursor c=getReadableDatabase().rawQuery("SELECT DISTINCT merchant FROM tx WHERE category='Uncategorised' AND manualCategory=0 ORDER BY time DESC",null)){while(c.moveToNext()&&merchants.size()<3){String m=c.getString(0);if(m.toLowerCase(java.util.Locale.ROOT).contains(q)&&!m.equalsIgnoreCase("Unknown"))merchants.add(m);}}return merchants;}
 public int applyAutoCategory(String merchant,String category){if(category.equals("Uncategorised"))return 0;ContentValues v=new ContentValues();v.put("category",category);return getWritableDatabase().update("tx",v,"LOWER(TRIM(merchant))=? AND category='Uncategorised' AND manualCategory=0",new String[]{merchant.trim().toLowerCase(java.util.Locale.ROOT)});}
 public void plan(String name,long amount,String date){ContentValues v=new ContentValues();v.put("name",name);v.put("amount",amount);v.put("date",date);getWritableDatabase().insert("plans",null,v);}
 public void removePlan(long id){getWritableDatabase().delete("plans","id=?",new String[]{""+id});}
 public void clear(){SQLiteDatabase d=getWritableDatabase();d.execSQL("DELETE FROM tx");d.execSQL("DELETE FROM plans");d.execSQL("DELETE FROM rules");}
 private static String hash(String s){try{byte[] b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder x=new StringBuilder();for(byte v:b)x.append(String.format("%02x",v));return x.toString();}catch(Exception e){throw new IllegalStateException(e);}}
}
